language: generic
services:
    - docker

install:
    - travis_wait 120 sleep infinity &
    - docker build -t docker-gentoo-xdistccd-rpi . > /dev/null

script:
    - echo $(docker images) | grep "docker-gentoo-xdistccd-rpi"
